# Generated by Django 3.0.1 on 2020-05-21 10:15

import attributes.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.TextField(verbose_name='Value')),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1024, verbose_name='Description')),
                ('max_values', models.IntegerField(default=1023, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1023)], verbose_name='Max Values')),
                ('max_owner_perms', models.SmallIntegerField(choices=[(0, 'None'), (1, 'Read'), (3, 'Read Write')], default=0, verbose_name='Max Owner Permissions')),
                ('max_all_perms', models.SmallIntegerField(choices=[(0, 'None'), (1, 'Read'), (3, 'Read Write')], default=0, verbose_name='Max Non-Owner Permissions')),
                ('name', models.CharField(max_length=63, verbose_name='Key Name')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(default=attributes.models.epoch_start, verbose_name='Deleted at')),
                ('label', models.CharField(max_length=32, verbose_name='Label')),
                ('is_editable', models.BooleanField(default=False, verbose_name='Is Editable')),
                ('format_description', models.CharField(max_length=256, verbose_name='Description of the format')),
                ('format_regex', models.TextField(verbose_name='Regex for formatter')),
            ],
        ),
        migrations.CreateModel(
            name='AttributeApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('REVOKED', 'Revoked'), ('PENDING', 'Pending')], default='PENDING', max_length=8)),
                ('max_perms', models.SmallIntegerField(choices=[(0, 'None'), (1, 'Read'), (3, 'Read Write')], default=0, verbose_name='Max Non-Owner Permissions')),
            ],
        ),
        migrations.CreateModel(
            name='AttributeData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('attr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attributes.Attribute')),
            ],
        ),
    ]
