# Generated by Django 3.0.1 on 2020-05-21 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_GRANT_MODEL),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        ('attributes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributedata',
            name='owning_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owning_app', to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        ),
        migrations.AddField(
            model_name='attributedata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes_attributedata', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attributeapproval',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attributes.Attribute'),
        ),
        migrations.AddField(
            model_name='attributeapproval',
            name='grant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.OAUTH2_PROVIDER_GRANT_MODEL),
        ),
        migrations.AddField(
            model_name='attributeapproval',
            name='owning_app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes_owning_app', to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        ),
        migrations.AddField(
            model_name='attributeapproval',
            name='requesting_app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes_requesting_app', to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        ),
        migrations.AddField(
            model_name='attributeapproval',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes_attributeapproval', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attribute',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        ),
        migrations.AddField(
            model_name='allowedvalue',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attributes.Attribute'),
        ),
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together={('application', 'name')},
        ),
    ]
