# Generated by Django 3.0.1 on 2020-05-21 10:15

import api.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('status', models.CharField(choices=[('Accepted', 'ACCEPTED'), ('Pending', 'PENDING'), ('Cancelled', 'CANCELLED')], default='Cancelled', max_length=32, verbose_name='status')),
                ('ip_address', models.CharField(max_length=64, verbose_name='ip address')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('verified_on', models.DateTimeField(default=api.models.long_time_from_now)),
                ('verification_code', models.CharField(max_length=128, verbose_name='Verification Code')),
            ],
        ),
        migrations.CreateModel(
            name='IdentityVerificationSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneVerificationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=31, verbose_name='phone number')),
                ('status', models.CharField(choices=[('Accepted', 'ACCEPTED'), ('Pending', 'PENDING'), ('Cancelled', 'CANCELLED')], default='Pending', max_length=32, verbose_name='status')),
                ('ip_address', models.CharField(max_length=64, verbose_name='ip address')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('verified_on', models.DateTimeField(default=api.models.long_time_from_now)),
                ('verification_code', models.CharField(max_length=128, verbose_name='Verification Code')),
            ],
        ),
        migrations.CreateModel(
            name='ResetPasswordSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=32, verbose_name='status')),
                ('ip_address', models.CharField(max_length=64, verbose_name='ip address')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('verification_code', models.CharField(max_length=128, verbose_name='Verification Code')),
            ],
        ),
        migrations.CreateModel(
            name='SecondFactorAuthSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoded_code', models.CharField(max_length=128, verbose_name='encoded code')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('verified_on', models.DateTimeField()),
                ('exchanged_on', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UnsubscribedEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('nonce', models.CharField(max_length=256, verbose_name='nonce')),
                ('hash', models.CharField(max_length=128, verbose_name='hash')),
            ],
        ),
    ]
