# Generated by Django 3.0.1 on 2020-05-21 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='unsubscribedemail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_unsubscribedemail', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='secondfactorauthsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_secondfactorauthsession', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resetpasswordsession',
            name='second_factor_auth_sess',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SecondFactorAuthSession'),
        ),
        migrations.AddField(
            model_name='resetpasswordsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_resetpasswordsession', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phoneverificationsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_phoneverificationsession', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='identityverificationsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_identityverificationsession', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailverificationsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_emailverificationsession', to=settings.AUTH_USER_MODEL),
        ),
    ]
