# Generated by Django 3.0.6 on 2020-08-18 11:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yggdrasil', '0001_initial'),
        ('pdp2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JSONStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Json Data')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yggdrasil.Dataset')),
                ('txn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdp2.Pdp2Transaction')),
                ('created_on', models.DateTimeField(auto_now_add=True)),

            ],
        ),
    ]
