# Generated by Django 3.0.6 on 2020-10-13 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yggdrasil', '0004_data_data_file'),
        ('pdp2', '0003_torrent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatedStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FileField(upload_to='development/aggregated_data', verbose_name='Aggregated Data')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yggdrasil.Dataset')),
                ('txn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdp2.Pdp2Transaction')),
            ],
        ),
    ]
