# Generated by Django 3.0.1 on 2020-05-21 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import identity_verification.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GovIdVerificationSession',
            fields=[
                ('full_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='full name')),
                ('status', models.CharField(choices=[('Accepted', 'ACCEPTED'), ('Accepted & Inactive', 'ACCEPTED_INACTIVE'), ('Pending', 'PENDING'), ('Rejected', 'REJECTED'), ('Incomplete', 'INCOMPLETE'), ('Cancelled', 'CANCELLED')], default='Incomplete', max_length=32, verbose_name='status')),
                ('verification_words', models.CharField(default=identity_verification.models.get_randomized_words, max_length=256, verbose_name='verification words')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('reviewed_on', models.DateTimeField(blank=True, null=True)),
                ('verified_on', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(max_length=256, verbose_name='rejection reason')),
                ('ip_address', models.CharField(max_length=64, verbose_name='ip address')),
                ('video_content_type', models.CharField(max_length=64, verbose_name='video content type')),
                ('video', models.FileField(blank=True, null=True, upload_to='', verbose_name="User's video verification")),
                ('verification_request', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
