export const ActionTypes = {
  GET_PDP2_TXNS_LIST_REQUEST: 'GET_PDP2_TXNS_LIST_REQUEST',
  GET_PDP2_TXNS_LIST_SUCCESS: 'GET_PDP2_TXNS_LIST_SUCCESS',
  GET_PDP2_TXNS_LIST_FAILURE: 'GET_PDP2_TXNS_LIST_FAILURE',

  GET_PDP2_DATASETS_LIST_REQUEST: 'GET_PDP2_DATASETS_LIST_REQUEST',
  GET_PDP2_DATASETS_LIST_SUCCESS: 'GET_PDP2_DATASETS_LIST_SUCCESS',
  GET_PDP2_DATASETS_LIST_FAILURE: 'GET_PDP2_DATASETS_LIST_FAILURE',

  GET_PAI_MESSAGES_THREAD_LIST_REQUEST: 'GET_PAI_MESSAGES_THREAD_LIST_REQUEST',
  GET_PAI_MESSAGES_THREAD_LIST_SUCCESS: 'GET_PAI_MESSAGES_THREAD_LIST_SUCCESS',
  GET_PAI_MESSAGES_THREAD_LIST_FAILURE: 'GET_PAI_MESSAGES_THREAD_LIST_FAILURE',

  GET_PAI_MESSAGES_MSG_LIST_REQUEST: 'GET_PAI_MESSAGES_MSG_LIST_REQUEST',
  GET_PAI_MESSAGES_MSG_LIST_SUCCESS: 'GET_PAI_MESSAGES_MSG_LIST_SUCCESS',
  GET_PAI_MESSAGES_MSG_LIST_FAILURE: 'GET_PAI_MESSAGES_MSG_LIST_FAILURE',

  ON_RECEIVE_PAI_MESSAGE_SUCCESS: 'ON_RECEIVE_PAI_MESSAGE_SUCCESS',
  ON_RECEIVE_PAI_MESSAGE_FAILURE: 'ON_RECEIVE_PAI_MESSAGE_FAILURE',

  ON_PAI_MESSAGES_THREAD_SWITCH: 'ON_PAI_MESSAGES_THREAD_SWITCH',
};