const FIELD_TYPE_DATE = 'DATE';
const FIELD_TYPE_TEXT = 'TEXT';
const FIELD_TYPE_OBJECT = 'OBJECT';
const FIELD_TYPE_LIST = 'LIST';
const FIELD_TYPE_VIDEO = 'VIDEO';
const FIELD_TYPE_IMAGE = 'IMAGE';
const FIELD_TYPE_FILE = 'FILE';
const FIELD_TYPE_PRIMITIVE = 'PRIMITIVE';

export {
  FIELD_TYPE_PRIMITIVE,
  FIELD_TYPE_DATE,
  FIELD_TYPE_TEXT,
  FIELD_TYPE_OBJECT,
  FIELD_TYPE_LIST,
  FIELD_TYPE_VIDEO,
  FIELD_TYPE_IMAGE,
  FIELD_TYPE_FILE,

}