# Generated by Django 3.0.6 on 2020-08-21 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('everyone', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yggdrasil_sharegroup', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserShareGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yggdrasil.ShareGroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yggdrasil_usersharegroup', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('storage_provider', models.CharField(choices=[('S3', 'S3'), ('PDP2', 'PDP2')], default='PDP2', max_length=32, verbose_name='Storage Provider')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('share_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yggdrasil.ShareGroup')),
                ('reusable', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('share_group', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('data_type', models.CharField(choices=[('Text', 'TEXT'), ('Date', 'DATE'), ('Object', 'OBJECT'), ('List', 'LIST'), ('Integer', 'INTEGER')], default='Text', max_length=64)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yggdrasil.Schema')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yggdrasil.Field')),
            ],
            options={
                'unique_together': {('schema', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yggdrasil.Schema')),
                ('share_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yggdrasil.ShareGroup')),
                ('watched_by', models.CharField(choices=[('Pdp2', 'PDP2'), ], null=True, blank=True, max_length=64, verbose_name="Watched By")),

            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(verbose_name='Value')),
                ('private', models.BooleanField(default=False, verbose_name='Private')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yggdrasil.Dataset')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yggdrasil.Field')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': set(),
            },
        ),
    ]
