# Generated by Django 3.0.6 on 2020-10-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yggdrasil', '0002_known_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='data_type',
            field=models.CharField(choices=[('Text', 'TEXT'), ('Date', 'DATE'), ('Object', 'OBJECT'), ('List', 'LIST'), ('File', 'FILE'), ('Image', 'IMAGE'), ('Video', 'VIDEO'), ('Integer', 'INTEGER')], default='Text', max_length=64),
        ),
    ]
