# Generated by Django 3.0.6 on 2020-10-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yggdrasil', '0003_auto_20201011_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='data_file',
            field=models.FileField(null=True, upload_to='development/yggdrasil', verbose_name='File corresponding to yggdrasil data'),
        ),
    ]
