# Generated by Django 3.0.6 on 2020-11-04 02:13

from django.db import migrations, models
import yggdrasil.models


class Migration(migrations.Migration):

    dependencies = [
        ('yggdrasil', '0004_data_data_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='data_file',
            field=models.FileField(null=True, upload_to=yggdrasil.models.upload_to_fn, verbose_name='File corresponding to yggdrasil data'),
        ),
    ]
