class PAICOIN_PAI_PDP2_PROTOCOL:
    # HEADER
    PAI_DELIMITER_SZ = 1  #
    VERSION_SZ = 1
    RESERVED_SZ = 6
    # PAYLOAD
    OPERATION_SZ = 1
    STORAGE_METHOD_SZ = 1
    OP1_SZ_SZ = 1
    OP1_SZ = 32

    OP2_SZ_SZ = 1
    OP2_SZ = 32
    CHECKSUM_SZ = 4

# Needs to be upper case or it won't work
class BITCOIN_PAI_PDP2_PROTOCOL(PAICOIN_PAI_PDP2_PROTOCOL):
    # HEADER
    # Since we only have 40 bytes we leave out the header to fit the rest in.
    PAI_DELIMITER_SZ = 0
    VERSION_SZ = 0
    RESERVED_SZ = 0

    # We additionally leave  out the checksum.
    CHECKSUM_SZ = 0

    OP_RETURN_SIZE = 40

    OP1_SZ = OP_RETURN_SIZE - PAI_DELIMITER_SZ - VERSION_SZ - PAICOIN_PAI_PDP2_PROTOCOL.OPERATION_SZ \
             - PAICOIN_PAI_PDP2_PROTOCOL.STORAGE_METHOD_SZ - PAICOIN_PAI_PDP2_PROTOCOL.OP1_SZ_SZ \
             - PAICOIN_PAI_PDP2_PROTOCOL.OP2_SZ_SZ - PAICOIN_PAI_PDP2_PROTOCOL.OP2_SZ - CHECKSUM_SZ

PAI_PDP2_PROTOCOL = BITCOIN_PAI_PDP2_PROTOCOL

print('BITCOIN OP1 Size:', PAI_PDP2_PROTOCOL.OP1_SZ)
print('PAICOIN OP1 Size:', PAICOIN_PAI_PDP2_PROTOCOL.OP1_SZ)

